# Generated by Django 4.0.6 on 2022-08-15 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=280)),
                ('time', models.DateTimeField()),
                ('likes', models.ManyToManyField(blank=True, null=True, related_name='allLikedUser', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=models.SET('Deleted user'), related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
